[uwsgi]
 # main - file name, app - var name in the file
module = main:app

# master = true
# processes = 5

enable-threads = true
http-socket = 0.0.0.0:80
# socket = /tmp/uwsgi.sock
# buffer-size = 32768

uid = python
gid = python

die-on-term = true
