version: '3.8'

services:
  azure.adauth:
    build:
      context: .
      dockerfile: ../Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./.infra/.env
    ports:
      - 8000:80
