//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountryInfoServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo", ConfigurationName="CountryInfoServiceReference.CountryInfoServiceSoapType")]
    public interface CountryInfoServiceSoapType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tContinent[]> ListOfContinentsByNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tContinent[]> ListOfContinentsByCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tCurrency[]> ListOfCurrenciesByNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tCurrency[]> ListOfCurrenciesByCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CurrencyNameAsync(string sCurrencyISOCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tCountryCodeAndName[]> ListOfCountryNamesByCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tCountryCodeAndName[]> ListOfCountryNamesByNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tCountryCodeAndNameGroupedByContinent[]> ListOfCountryNamesGroupedByContinentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CountryNameAsync(string sCountryISOCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CountryISOCodeAsync(string sCountryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CapitalCityAsync(string sCountryISOCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tCurrency> CountryCurrencyAsync(string sCountryISOCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CountryFlagAsync(string sCountryISOCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CountryIntPhoneCodeAsync(string sCountryISOCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tCountryInfo> FullCountryInfoAsync(string sCountryISOCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tCountryInfo[]> FullCountryInfoAllCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tCountryCodeAndName[]> CountriesUsingCurrencyAsync(string sISOCurrencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tLanguage[]> ListOfLanguagesByNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CountryInfoServiceReference.tLanguage[]> ListOfLanguagesByCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LanguageNameAsync(string sISOCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LanguageISOCodeAsync(string sLanguageName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tContinent
    {
        
        private string sCodeField;
        
        private string sNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sCode
        {
            get
            {
                return this.sCodeField;
            }
            set
            {
                this.sCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tLanguage
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryInfo
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        private string sCapitalCityField;
        
        private string sPhoneCodeField;
        
        private string sContinentCodeField;
        
        private string sCurrencyISOCodeField;
        
        private string sCountryFlagField;
        
        private tLanguage[] languagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sCapitalCity
        {
            get
            {
                return this.sCapitalCityField;
            }
            set
            {
                this.sCapitalCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sPhoneCode
        {
            get
            {
                return this.sPhoneCodeField;
            }
            set
            {
                this.sPhoneCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sContinentCode
        {
            get
            {
                return this.sContinentCodeField;
            }
            set
            {
                this.sContinentCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sCurrencyISOCode
        {
            get
            {
                return this.sCurrencyISOCodeField;
            }
            set
            {
                this.sCurrencyISOCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sCountryFlag
        {
            get
            {
                return this.sCountryFlagField;
            }
            set
            {
                this.sCountryFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public tLanguage[] Languages
        {
            get
            {
                return this.languagesField;
            }
            set
            {
                this.languagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryCodeAndNameGroupedByContinent
    {
        
        private tContinent continentField;
        
        private tCountryCodeAndName[] countryCodeAndNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tContinent Continent
        {
            get
            {
                return this.continentField;
            }
            set
            {
                this.continentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public tCountryCodeAndName[] CountryCodeAndNames
        {
            get
            {
                return this.countryCodeAndNamesField;
            }
            set
            {
                this.countryCodeAndNamesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryCodeAndName
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCurrency
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CountryInfoServiceSoapTypeChannel : CountryInfoServiceReference.CountryInfoServiceSoapType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CountryInfoServiceSoapTypeClient : System.ServiceModel.ClientBase<CountryInfoServiceReference.CountryInfoServiceSoapType>, CountryInfoServiceReference.CountryInfoServiceSoapType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CountryInfoServiceSoapTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(CountryInfoServiceSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), CountryInfoServiceSoapTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CountryInfoServiceSoapTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CountryInfoServiceSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CountryInfoServiceSoapTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CountryInfoServiceSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CountryInfoServiceSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tContinent[]> ListOfContinentsByNameAsync()
        {
            return base.Channel.ListOfContinentsByNameAsync();
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tContinent[]> ListOfContinentsByCodeAsync()
        {
            return base.Channel.ListOfContinentsByCodeAsync();
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tCurrency[]> ListOfCurrenciesByNameAsync()
        {
            return base.Channel.ListOfCurrenciesByNameAsync();
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tCurrency[]> ListOfCurrenciesByCodeAsync()
        {
            return base.Channel.ListOfCurrenciesByCodeAsync();
        }
        
        public System.Threading.Tasks.Task<string> CurrencyNameAsync(string sCurrencyISOCode)
        {
            return base.Channel.CurrencyNameAsync(sCurrencyISOCode);
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tCountryCodeAndName[]> ListOfCountryNamesByCodeAsync()
        {
            return base.Channel.ListOfCountryNamesByCodeAsync();
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tCountryCodeAndName[]> ListOfCountryNamesByNameAsync()
        {
            return base.Channel.ListOfCountryNamesByNameAsync();
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tCountryCodeAndNameGroupedByContinent[]> ListOfCountryNamesGroupedByContinentAsync()
        {
            return base.Channel.ListOfCountryNamesGroupedByContinentAsync();
        }
        
        public System.Threading.Tasks.Task<string> CountryNameAsync(string sCountryISOCode)
        {
            return base.Channel.CountryNameAsync(sCountryISOCode);
        }
        
        public System.Threading.Tasks.Task<string> CountryISOCodeAsync(string sCountryName)
        {
            return base.Channel.CountryISOCodeAsync(sCountryName);
        }
        
        public System.Threading.Tasks.Task<string> CapitalCityAsync(string sCountryISOCode)
        {
            return base.Channel.CapitalCityAsync(sCountryISOCode);
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tCurrency> CountryCurrencyAsync(string sCountryISOCode)
        {
            return base.Channel.CountryCurrencyAsync(sCountryISOCode);
        }
        
        public System.Threading.Tasks.Task<string> CountryFlagAsync(string sCountryISOCode)
        {
            return base.Channel.CountryFlagAsync(sCountryISOCode);
        }
        
        public System.Threading.Tasks.Task<string> CountryIntPhoneCodeAsync(string sCountryISOCode)
        {
            return base.Channel.CountryIntPhoneCodeAsync(sCountryISOCode);
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tCountryInfo> FullCountryInfoAsync(string sCountryISOCode)
        {
            return base.Channel.FullCountryInfoAsync(sCountryISOCode);
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tCountryInfo[]> FullCountryInfoAllCountriesAsync()
        {
            return base.Channel.FullCountryInfoAllCountriesAsync();
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tCountryCodeAndName[]> CountriesUsingCurrencyAsync(string sISOCurrencyCode)
        {
            return base.Channel.CountriesUsingCurrencyAsync(sISOCurrencyCode);
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tLanguage[]> ListOfLanguagesByNameAsync()
        {
            return base.Channel.ListOfLanguagesByNameAsync();
        }
        
        public System.Threading.Tasks.Task<CountryInfoServiceReference.tLanguage[]> ListOfLanguagesByCodeAsync()
        {
            return base.Channel.ListOfLanguagesByCodeAsync();
        }
        
        public System.Threading.Tasks.Task<string> LanguageNameAsync(string sISOCode)
        {
            return base.Channel.LanguageNameAsync(sISOCode);
        }
        
        public System.Threading.Tasks.Task<string> LanguageISOCodeAsync(string sLanguageName)
        {
            return base.Channel.LanguageISOCodeAsync(sLanguageName);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso");
            }
            if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CountryInfoServiceSoap,
            
            CountryInfoServiceSoap12,
        }
    }
}
