version: '3.8'

services:
  azure.adauth:
    build:
      context: Azure.ADAuth
      dockerfile: ../Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./Azure.ADAuth/.infra/.env
    ports:
      - 8000:80

  azure.blob:
    build:
      context: Azure.Blob
      dockerfile: ../Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./Azure.Blob/.infra/.env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 30M
        reservations:
          cpus: '1'
          memory: 30M
    ports:
      - 8001:80

  azure.function:
    build:
      context: Azure.Function
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./Azure.Function/.infra/.env
    ports:
      - 8002:80
