version: '3.8'

services:
  azure.adauth:
    build:
      context: Azure.ADAuth
      dockerfile: ../Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./Azure.ADAuth/.infra/.env
    ports:
      - 8000:80
