ARG AZ_FUNCTION_IMAGE

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src

RUN dotnet tool install dotnet-counters --version 6.* --tool-path /publish \
    && dotnet tool install dotnet-dump --version 6.* --tool-path /publish \
    && dotnet tool install dotnet-trace --version 6.* --tool-path /publish \
    && chmod +x /publish/dotnet-*

COPY *.csproj ./
RUN dotnet restore

COPY . .

RUN mv *.csproj App.csproj \
    && dotnet publish -o /publish

FROM mcr.microsoft.com/azure-functions/$AZ_FUNCTION_IMAGE

WORKDIR /app

ENV AzureWebJobsScriptRoot=/app \
    AzureWebJobsSecretStorageType=files \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

RUN mkdir -p /azure-functions-host/Secrets/ \
    && echo '{"masterKey":{"name":"master","value":"test","encrypted":false},"functionKeys":[]}' > /azure-functions-host/Secrets/host.json

COPY --from=build /publish .