version: '3.8'

services:
  azure.functionisolated:
    build:
      context: .
      dockerfile: ../Dockerfile.AzureFunc
      args:
        AZ_FUNCTION_IMAGE: dotnet-isolated:4-slim
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./.infra/.env
    ports:
      - 8000:80
